MWINDOW_WIDTH = 300
MWINDOW_HEIGHT = 420

WWINDOW_WIDTH = 280
WWINDOW_HEIGHT = 260

BACKGROUND_COLOR = "#2F3037"
BORDER_WIDTH = 3

DEFAULT_FONT = "Papyrus"
DEFAULT_FONT2 = "Comic Sans MS"

USERNAME = ""